version: '3.7'

services:

  mqtt:
    image: eclipse-mosquitto:1.4.12
    restart: always
    # ports:
    #  - "2883:1883"
    #  - "29001:9001"

  nodered:
    #image: kalemena/node-red:latest
    build: src/node-red
    restart: always
    ports:
     - "2880:1880"
    volumes:
     - ./src/node-red/flows:/opt/flows
     - ./etc/data:/opt/data
     - ./etc/node-red:/root/.node-red
    environment:
     - FLOWS=/opt/flows/tidhome-flows.json
