version: '3.7'
services:

  nodered:
    image: kalemena/node-red:0.20.5
    restart: always
    ports:
     - "2880:1880"
    volumes:
     - ./src/node-red/flows:/opt/flows
    environment:
     - FLOWS=/opt/flows/tidhome-flows.json
