version: '3.7'

services:

  mqtt:
    image: eclipse-mosquitto:1.4.12
    restart: always
    # ports:
    #  - "2883:1883"
    #  - "29001:9001"

  deconz:
    image: marthoc/deconz
    restart: always
    ports:
      - 7080:7080
      - 7443:7443
    volumes:
      - ./src/tidhome/etc/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyZigbee
    environment:
      - DECONZ_DEVICE=/dev/ttyZigbee
      - DECONZ_WEB_PORT=7080
      - DECONZ_WS_PORT=7443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0

  nodered:
    #image: kalemena/node-red:latest
    build: src/tidhome
    restart: always
    ports:
     - "2880:1880"
    volumes:
     - ./src/tidhome:/opt/tidhome
     - ./src/tidhome/config:/home/nodered/.node-red
     - ./var/log:/var/log
    devices:
     - "/dev/ttyCurrenCost:/dev/ttyCurrenCost"
     - "/dev/ttyJeeLink:/dev/ttyJeeLink"
     - "/dev/ttyZWave:/dev/ttyZWave"
    environment:
     - FLOWS=/opt/tidhome/flows/tidhome-flows.json

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /opt/home-assistant:/config
    environment:
      - TZ=Europe/Paris
    restart: always
    network_mode: host