FROM kalemena/node-red:1.0.2

RUN npm i \
    node-red-contrib-file-function \
    node-red-contrib-string \
    node-red-contrib-fs \
    node-red-contrib-readdir \
    node-red-contrib-telegrambot \
    node-red-node-darksky \
    node-red-contrib-simple-weekly-scheduler;